#
# Copyright (c) 2020 Red Hat, Inc.
# This program and the accompanying materials are made
# available under the terms of the Eclipse Public License 2.0
# which is available at https://www.eclipse.org/legal/epl-2.0/
#
# SPDX-License-Identifier: EPL-2.0
#

name: Build Che-Theia

on: [push, pull_request, workflow_dispatch]

jobs:
  node-build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      name: Checkout che-theia source code
    - uses: actions/setup-node@v1
      name: Configuring nodejs 10.x version
      with:
        node-version: '12.x'
    - name: build
      run: yarn
  docker-build-and-push:
    runs-on: ubuntu-latest
    steps:
    - name: Login to Docker Hub
      uses: docker/login-action@v1
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
    - uses: actions/checkout@v2
      name: Checkout che-theia source code
      with:
        repository: "eclipse/che-theia"
    - uses: actions/setup-node@v1
      name: Configuring nodejs 10.x version
      with:
        node-version: '12.x'
    - name: build
      run: |
        docker image prune -a -f
        docker pull quay.io/eclipse/che-theia-dev:next
        docker tag quay.io/eclipse/che-theia-dev:next eclipse/che-theia-dev:next
        # add our extension repo to the extension to be included in the che-theia build
        echo "- source: https://github.com/OpenTOSCA/che-winery-extension.git" >> che-theia-init-sources.yml
        ./build.sh --root-yarn-opts:--ignore-scripts --dockerfile:Dockerfile.alpine
        docker tag eclipse/che-theia:next opentosca/che-theia:next
        docker push opentosca/che-theia:next
